### ISSUE TITLE
save_screenshot failure (missing Pillow dependency in requirements.txt)

### ISSUE THREAD

**Issue by micmarty** [GokulNC/Setting-Up-CARLA-RL#2]
Run:
```bash
python human_play.py
```
with `save_screens=True` :

```python
env = CarlaEnv(is_render_enabled=False, 
num_speedup_steps = 10, 
run_offscreen=True, cameras = ['SceneFinal'], 
save_screens=True)
```

and uncommented `env.save_screenshots()`

```python
for _ in range(frame_skip):
		observation, reward, done, _ = env.step(action_map[tuple(action)])
		#env.render()
		env.save_screenshots()
		r += reward
		if done: break
```

Error:

```bash
pygame 1.9.4
Hello from the pygame community. https://www.pygame.org/contribute.html
Creating Environment..
Resetting the environment..
Start playing..... :)
Traceback (most recent call last):
  File "human_play.py", line 91, in <module>
    env.save_screenshots()
  File "/home/miczi/Repos/Setting-Up-CARLA-RL/Environment/carla_environment_wrapper.py", line 433, in save_screenshots
    save_image(self.rgb_img_path+filename+".png", self.observation['rgb_image'])
  File "/home/miczi/Repos/Setting-Up-CARLA-RL/Environment/utils.py", line 88, in save_image
    scipy.misc.toimage(npimg).save(outfilename)
AttributeError: module 'scipy.misc' has no attribute 'toimage'
```

Fix:
Installing `pip install Pillow` solves this issue

BTW Awesome job! I love this wrapper!

**Comment by GokulNC** [comment]
Thank you @micmarty .
I've fixed this issue :)

**Comment by GokulNC** [comment]
Is it working now??
