### ISSUE TITLE
No module named 'carla.client'

### ISSUE THREAD

**Issue by kk2491** [GokulNC/Setting-Up-CARLA-RL#3]
Hi,

Thanks for the wonderful repository.

I have some questions about the initial setup of the Environment.

I am using Carla Compiled version 0.9.2 and python3, when I try to run ```from Environment.carla_environment_wrapper import CarlaEnvironmentWrapper as CarlaEnv``` as mentioned in the Readme I am getting the below error.

```
>>> from Environment.carla_environment_wrapper import CarlaEnvironmentWrapper as CarlaEnv
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kishor/GWM/Reinforcement_Learning/Setting-Up-CARLA-RL/Environment/carla_environment_wrapper.py", line 9, in <module>
    from carla.client import CarlaClient
ImportError: No module named 'carla.client'
>>> 
```

Note : I can import carla without any issues.

Thank you,
KK

**Comment by GokulNC** [comment]
Hi,

I'm sorry, but as of now, this repo was tested only on Carla versions 0.8.*
I think it won't work on any versions above this since there were some major changes in their APIs.
So, please try to fix them yourself, or I'll do it when I find time :)

Also, if you're making any changes and get it working on newer versions, please feel free to send me a pull request with the changes. I'll be glad to integrate them with proper credits ;)

**Comment by kk2491** [comment]
@GokulNC Thanks for the reply. Let me check if I can find the fix.

**Comment by JarvisIsFriday** [comment]
> @GokulNC Thanks for the reply. Let me check if I can find the fix.

Hello,I met the same problem of yours tested on Carla versions 0.9.6.
Have you found the fix？Thanks.

**Comment by hamdii02** [comment]
@JarvisIsFriday Hello, have you find a solution for the Carla version 0..9.6 ?
